// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrevisionMax.Data;

#nullable disable

namespace PrevisionMaxApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240702121423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrevisionMax.Models.EstatisticaTimesCasa", b =>
                {
                    b.Property<int>("IdEstatisticaCasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatisticaCasa"));

                    b.Property<int>("AtaquesperigososCasa")
                        .HasColumnType("int");

                    b.Property<int>("CartoesAmareloCasa")
                        .HasColumnType("int");

                    b.Property<int>("CartoesVermelhosCasa")
                        .HasColumnType("int");

                    b.Property<int>("DefesaGoleiroCasa")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCasas")
                        .HasColumnType("int");

                    b.Property<int>("GolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("InpedimentosCasa")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeCasa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("PassesCompletosCasa")
                        .HasColumnType("int");

                    b.Property<int>("PassesTotaisCasa")
                        .HasColumnType("int");

                    b.Property<int>("TentativasGolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("chutesnoGolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("chutespraforaCasa")
                        .HasColumnType("int");

                    b.Property<int>("escanteiosCasa")
                        .HasColumnType("int");

                    b.HasKey("IdEstatisticaCasa");

                    b.ToTable("Tb_EstatisticaCasa", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstatisticaCasa = 1,
                            AtaquesperigososCasa = 0,
                            CartoesAmareloCasa = 0,
                            CartoesVermelhosCasa = 0,
                            DefesaGoleiroCasa = 0,
                            FaltasCasas = 0,
                            GolsCasa = 99,
                            InpedimentosCasa = 0,
                            NomeTimeCasa = "Palmeiras",
                            PassesCompletosCasa = 0,
                            PassesTotaisCasa = 0,
                            TentativasGolsCasa = 0,
                            chutesnoGolsCasa = 0,
                            chutespraforaCasa = 0,
                            escanteiosCasa = 0
                        },
                        new
                        {
                            IdEstatisticaCasa = 2,
                            AtaquesperigososCasa = 0,
                            CartoesAmareloCasa = 0,
                            CartoesVermelhosCasa = 0,
                            DefesaGoleiroCasa = 0,
                            FaltasCasas = 0,
                            GolsCasa = -31,
                            InpedimentosCasa = 0,
                            NomeTimeCasa = "Cortinas",
                            PassesCompletosCasa = 0,
                            PassesTotaisCasa = 0,
                            TentativasGolsCasa = 0,
                            chutesnoGolsCasa = 0,
                            chutespraforaCasa = 0,
                            escanteiosCasa = 0
                        },
                        new
                        {
                            IdEstatisticaCasa = 3,
                            AtaquesperigososCasa = 0,
                            CartoesAmareloCasa = 0,
                            CartoesVermelhosCasa = 0,
                            DefesaGoleiroCasa = 0,
                            FaltasCasas = 0,
                            GolsCasa = 2,
                            InpedimentosCasa = 0,
                            NomeTimeCasa = "Flamengo",
                            PassesCompletosCasa = 0,
                            PassesTotaisCasa = 0,
                            TentativasGolsCasa = 0,
                            chutesnoGolsCasa = 0,
                            chutespraforaCasa = 0,
                            escanteiosCasa = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
