// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrevisionMax.Data;

#nullable disable

namespace PrevisionMaxApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrevisionMax.Models.Classificacao", b =>
                {
                    b.Property<int>("idClassficacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idClassficacao"));

                    b.Property<int>("GolsFeitos")
                        .HasColumnType("int");

                    b.Property<int>("GolsSofridos")
                        .HasColumnType("int");

                    b.Property<string>("NomeTime")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoTime")
                        .HasColumnType("int");

                    b.Property<int>("numDerrotas")
                        .HasColumnType("int");

                    b.Property<int>("numEmpates")
                        .HasColumnType("int");

                    b.Property<int>("numJogos")
                        .HasColumnType("int");

                    b.Property<int>("numVitorias")
                        .HasColumnType("int");

                    b.Property<string>("ultiomojogos1")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<string>("ultiomojogos2")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<string>("ultiomojogos3")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<string>("ultiomojogos4")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<string>("ultiomojogos5")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.HasKey("idClassficacao");

                    b.ToTable("TB_Classificacao", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.EstatisticaTimes", b =>
                {
                    b.Property<int>("IdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTime"));

                    b.Property<float>("AtaquesperigososMedia")
                        .HasColumnType("real");

                    b.Property<float>("AtaquesperigososMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("CartoesAmareloMaior")
                        .HasColumnType("int");

                    b.Property<float>("CartoesAmareloMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("CartoesAmareloMedia")
                        .HasColumnType("real");

                    b.Property<float>("CartoesAmareloMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("CartoesAmareloMenor")
                        .HasColumnType("int");

                    b.Property<float>("CartoesAmareloMenorCF")
                        .HasColumnType("real");

                    b.Property<float>("CartoesVermelhosMedia")
                        .HasColumnType("real");

                    b.Property<int>("DefesaGoleiroMaior")
                        .HasColumnType("int");

                    b.Property<float>("DefesaGoleiroMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("DefesaGoleiroMedia")
                        .HasColumnType("real");

                    b.Property<float>("DefesaGoleiroMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("DefesaGoleiroMenor")
                        .HasColumnType("int");

                    b.Property<float>("DefesaGoleiroMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("FaltasMaior")
                        .HasColumnType("int");

                    b.Property<float>("FaltasMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("FaltasMedia")
                        .HasColumnType("real");

                    b.Property<float>("FaltasMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("FaltasMenor")
                        .HasColumnType("int");

                    b.Property<float>("FaltasMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("GolMaior")
                        .HasColumnType("int");

                    b.Property<float>("GolMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("GolMedias")
                        .HasColumnType("real");

                    b.Property<float>("GolMediasCF")
                        .HasColumnType("real");

                    b.Property<int>("GolMenor")
                        .HasColumnType("int");

                    b.Property<float>("GolMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("GolsSofridosMaior")
                        .HasColumnType("int");

                    b.Property<float>("GolsSofridosMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("GolsSofridosMedias")
                        .HasColumnType("real");

                    b.Property<float>("GolsSofridosMediasCF")
                        .HasColumnType("real");

                    b.Property<int>("GolsSofridosMenor")
                        .HasColumnType("int");

                    b.Property<float>("GolsSofridosMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("InpedimentosMaior")
                        .HasColumnType("int");

                    b.Property<float>("InpedimentosMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("InpedimentosMedia")
                        .HasColumnType("real");

                    b.Property<float>("InpedimentosMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("InpedimentosMenor")
                        .HasColumnType("int");

                    b.Property<float>("InpedimentosMenorCF")
                        .HasColumnType("real");

                    b.Property<string>("NomeTime")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<float>("PassesCompletosMedia")
                        .HasColumnType("real");

                    b.Property<float>("PassesCompletosMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("PassesTotaisMaior")
                        .HasColumnType("int");

                    b.Property<float>("PassesTotaisMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("PassesTotaisMedia")
                        .HasColumnType("real");

                    b.Property<float>("PassesTotaisMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("PassesTotaisMenor")
                        .HasColumnType("int");

                    b.Property<float>("PassesTotaisMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("TentativasGolsMaior")
                        .HasColumnType("int");

                    b.Property<float>("TentativasGolsMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("TentativasGolsMedias")
                        .HasColumnType("real");

                    b.Property<float>("TentativasGolsMediasCF")
                        .HasColumnType("real");

                    b.Property<int>("TentativasGolsMenor")
                        .HasColumnType("int");

                    b.Property<float>("TentativasGolsMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("chutesnoGolsMaior")
                        .HasColumnType("int");

                    b.Property<float>("chutesnoGolsMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("chutesnoGolsMedia")
                        .HasColumnType("real");

                    b.Property<float>("chutesnoGolsMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("chutesnoGolsMenor")
                        .HasColumnType("int");

                    b.Property<float>("chutesnoGolsMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("chutespraforaMaior")
                        .HasColumnType("int");

                    b.Property<float>("chutespraforaMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("chutespraforaMedia")
                        .HasColumnType("real");

                    b.Property<float>("chutespraforaMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("chutespraforaMenor")
                        .HasColumnType("int");

                    b.Property<float>("chutespraforaMenorCF")
                        .HasColumnType("real");

                    b.Property<int>("escanteiosMaior")
                        .HasColumnType("int");

                    b.Property<float>("escanteiosMaiorCF")
                        .HasColumnType("real");

                    b.Property<float>("escanteiosMedia")
                        .HasColumnType("real");

                    b.Property<float>("escanteiosMediaCF")
                        .HasColumnType("real");

                    b.Property<int>("escanteiosMenor")
                        .HasColumnType("int");

                    b.Property<float>("escanteiosMenorCF")
                        .HasColumnType("real");

                    b.HasKey("IdTime");

                    b.ToTable("Tb_EstatisticaTimes");
                });

            modelBuilder.Entity("PrevisionMax.Models.EstatisticaTimesCasa", b =>
                {
                    b.Property<int>("IdEstatisticaCasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatisticaCasa"));

                    b.Property<string>("AdversarioFora")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("AtaquesperigososCasa")
                        .HasColumnType("int");

                    b.Property<int?>("CartoesAmareloCasa")
                        .HasColumnType("int");

                    b.Property<int?>("CartoesVermelhosCasa")
                        .HasColumnType("int");

                    b.Property<int?>("DefesaGoleiroCasa")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCasas")
                        .HasColumnType("int");

                    b.Property<int>("GolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("GolsSofridosCasa")
                        .HasColumnType("int");

                    b.Property<int?>("InpedimentosCasa")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeCasa")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("PassesCompletosCasa")
                        .HasColumnType("int");

                    b.Property<int>("PassesTotaisCasa")
                        .HasColumnType("int");

                    b.Property<int>("TentativasGolsCasa")
                        .HasColumnType("int");

                    b.Property<int?>("chutesnoGolsCasa")
                        .HasColumnType("int");

                    b.Property<int>("chutespraforaCasa")
                        .HasColumnType("int");

                    b.Property<int?>("escanteiosCasa")
                        .HasColumnType("int");

                    b.HasKey("IdEstatisticaCasa");

                    b.ToTable("Tb_EstatisticaCasa", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.EstatisticaTimesFora", b =>
                {
                    b.Property<int>("IdEstatisticaFora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatisticaFora"));

                    b.Property<string>("AdversarioCasa")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("AtaquesperigososFora")
                        .HasColumnType("int");

                    b.Property<int?>("CartoesAmareloFora")
                        .HasColumnType("int");

                    b.Property<int?>("CartoesVermelhosFora")
                        .HasColumnType("int");

                    b.Property<int?>("DefesaGoleiroFora")
                        .HasColumnType("int");

                    b.Property<int>("FaltasForas")
                        .HasColumnType("int");

                    b.Property<int>("GolsFora")
                        .HasColumnType("int");

                    b.Property<int>("GolsSofridosFora")
                        .HasColumnType("int");

                    b.Property<int?>("InpedimentosFora")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeFora")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("PassesCompletosFora")
                        .HasColumnType("int");

                    b.Property<int>("PassesTotaisFora")
                        .HasColumnType("int");

                    b.Property<int>("TentativasGolsFora")
                        .HasColumnType("int");

                    b.Property<int?>("chutesnoGolsFora")
                        .HasColumnType("int");

                    b.Property<int>("chutespraforaFora")
                        .HasColumnType("int");

                    b.Property<int?>("escanteiosFora")
                        .HasColumnType("int");

                    b.HasKey("IdEstatisticaFora");

                    b.ToTable("Tb_EstatisticaFora", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.Palpites", b =>
                {
                    b.Property<int>("idPalpites")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPalpites"));

                    b.Property<string>("descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int>("idPartida")
                        .HasColumnType("int");

                    b.Property<double?>("num")
                        .HasColumnType("float");

                    b.Property<int>("tipoAposta")
                        .HasColumnType("int");

                    b.HasKey("idPalpites");

                    b.HasIndex("idPartida");

                    b.ToTable("TB_Palpites", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.Partidas", b =>
                {
                    b.Property<int>("idPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPartida"));

                    b.Property<string>("Campeonato")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<int?>("IdEstatisticaCasa")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstatisticaFora")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeCasa")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<string>("NomeTimeFora")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<bool>("PartidaAnalise")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPartida")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.HasKey("idPartida");

                    b.HasIndex("IdEstatisticaCasa");

                    b.HasIndex("IdEstatisticaFora");

                    b.ToTable("TB_Partidas", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.TabelaCampeonato", b =>
                {
                    b.Property<int>("idCampeonato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCampeonato"));

                    b.Property<string>("ClassificacaoIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCampeonato")
                        .HasMaxLength(200)
                        .HasColumnType("varChar");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.HasKey("idCampeonato");

                    b.ToTable("TB_TBCampeonato", (string)null);
                });

            modelBuilder.Entity("PrevisionMax.Models.Palpites", b =>
                {
                    b.HasOne("PrevisionMax.Models.Partidas", null)
                        .WithMany()
                        .HasForeignKey("idPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrevisionMax.Models.Partidas", b =>
                {
                    b.HasOne("PrevisionMax.Models.EstatisticaTimesCasa", null)
                        .WithMany()
                        .HasForeignKey("IdEstatisticaCasa");

                    b.HasOne("PrevisionMax.Models.EstatisticaTimesFora", null)
                        .WithMany()
                        .HasForeignKey("IdEstatisticaFora");
                });
#pragma warning restore 612, 618
        }
    }
}
